# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- script: |
    ./autogen.sh --prefix=/tmp/test-install --disable-nls --disable-btls --disable-boehm
  displayName: 'Autogen + Configure'

- script: |
    make
  displayName: 'Build Mono'

- script: |
    make install
  displayName: 'Install new version of Mono into /tmp'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    
  displayName: 'Run a multi-line script'
