# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: CI_TAGS=linux-amd64,all-profiles,apidiff,csprojdiff,bclsizediff,retry-flaky-tests,pull-request scripts/ci/run-jenkins.sh
  displayName: 'Run a one-line script'
